apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-cart
  template:
    metadata:
      labels:
        app: mysql-cart
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: cartdb
          ports:
            - containerPort: 3306